/**
 * ข้อมูลข่าวตัวอย่าง (หรือดึงจาก API จริงใน api.js)
 * โครง: { title, description, source, date, category, imageUrl, url }
 */

const MOCK_NEWS = [
  {
    id: "1",
    title: "เศรษฐกิจไทย Q4 ขยายตัวต่อเนื่อง การท่องเที่ยวฟื้นตัวดี",
    description: "หน่วยงานวิเคราะห์ชี้การบริโภคในประเทศและการส่งออกยังเป็นกำลังหลัก ขณะที่ภาคท่องเที่ยวมีแนวโน้มดีขึ้นอย่างต่อเนื่อง",
    source: "สำนักข่าวเศรษฐกิจ",
    date: "2025-03-08",
    category: "business",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "2",
    title: "เปิดตัวแพลตฟอร์ม AI ภาษาไทย รองรับภาครัฐและเอกชน",
    description: "บริษัทเทคฯ ไทยร่วมพัฒนาระบบประมวลผลภาษาธรรมชาติ รองรับการใช้งานในหน่วยงานราชการและองค์กรขนาดใหญ่",
    source: "TechThai",
    date: "2025-03-08",
    category: "tech",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "3",
    title: "ทีมชาติไทยเตรียมลุยศึก World Cup รอบคัดเลือก",
    description: "นักฟุตบอลทีมชาติไทยเริ่มเก็บตัวก่อนลงสนามนัดสำคัญในเดือนหน้า โค้ชย้ำความพร้อมทั้งแนวรุกและแนวรับ",
    source: "สยามกีฬา",
    date: "2025-03-07",
    category: "sports",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "4",
    title: "ครม. อนุมัติมาตรการช่วยเหลือผู้ได้รับผลกระทบจากภัยธรรมชาติ",
    description: "คณะรัฐมนตรีเห็นชอบวงเงินช่วยเหลือและมาตรการฟื้นฟูในหลายจังหวัดที่ประสบอุทกภัยและดินถล่ม",
    source: "รัฐบาลไทย",
    date: "2025-03-07",
    category: "general",
    imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "5",
    title: "ตลาดหุ้นไทยปิดบวกรับแรงซื้อจากต่างชาติ",
    description: "ดัชนี SET ปิดตลาดสูงขึ้นจากเมื่อวาน หลังเงินทุนต่างชาติไหลเข้าต่อเนื่องในกลุ่มหลักทรัพย์ที่มีแนวโน้มดี",
    source: "ตลาดหลักทรัพย์",
    date: "2025-03-08",
    category: "business",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "6",
    title: "ไทยติดอันดับต้นของโลกด้านการท่องเที่ยวเชิงสุขภาพ",
    description: "รายงานระดับโลกยกให้ไทยเป็นหนึ่งในจุดหมายยอดนิยมสำหรับการท่องเที่ยวเชิงสุขภาพและเวชศาสตร์การท่องเที่ยว",
    source: "การท่องเที่ยวแห่งประเทศไทย",
    date: "2025-03-06",
    category: "general",
    imageUrl: "https://images.unsplash.com/photo-1551918120-9739b430464f?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "7",
    title: "สตาร์ทอัปไทยได้เงินลงทุนรอบใหม่จากกองทุนในเอเชีย",
    description: "สตาร์ทอัปด้านฟินเทคและเอ็ดเทคได้รับเงินลงทุนรอบ Series B จากกองทุนในสิงคโปร์และญี่ปุ่น",
    source: "Startup Thailand",
    date: "2025-03-06",
    category: "tech",
    imageUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=380&fit=crop",
    url: "#",
  },
  {
    id: "8",
    title: "นักกีฬาไทยคว้าเหรียญทองในรายการเอเชียนเกมส์อินดอร์",
    description: "ทีมชาติไทยสร้างความภูมิใจด้วยการคว้าเหรียญทองในหลายชนิดกีฬา ทั้งเทควันโด ยิงปืน และว่ายน้ำ",
    source: "สมาคมกีฬาแห่งประเทศไทย",
    date: "2025-03-05",
    category: "sports",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ff164cacfc6f?w=600&h=380&fit=crop",
    url: "#",
  },
];

